// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DayToolsDotNet
{
    internal sealed partial class Vsix
    {
        public const string Id = "DayToolsDotNet.6941cce4-d305-4a89-976e-3d564e060bc1";
        public const string Name = "DayToolsDotNet";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
